const LocalizationKeys = {

        //#region  Headings

        ERP_HdrSelectedAndEquivalentExchangedPayment: { key: 'ERP_HdrSelectedAndEquivalentExchangedPayment', defaultText: 'Selected & Equivalent Exchanged Payment' },
        ERP_HdrExchangeHistory: { key: 'ERP_HdrExchangeHistory', defaultText: 'Exchange History' },
        ERP_HdrTransferDetails: { key: 'ERP_HdrTransferDetails', defaultText: 'Transfer Details' },
        ERP_HdrRecordANewTransfer: { key: 'ERP_HdrRecordANewTransfer', defaultText: 'Record a new  Transfer' },
        ERP_HdrProducts: { key: 'ERP_HdrProducts', defaultText: 'Products' },
        ERP_HdrSelectedPackageContents: { key: 'ERP_HdrSelectedPackageContents', defaultText: 'Selected PackageContents' },
        ERP_HdrSupportingDocuments: { key: "ERP_HdrSupportingDocuments", defaultText: 'Supporting Documents' },
        ERP_HdrCashOut: { key: 'ERP_HdrCashOut', defaultText: 'Cash Out' },
        ERP_HdrCashOutHistory: { key: 'ERP_HdrCashOutHistory', defaultText: 'Cash Out History' },
        ERP_HdrGenerateInvoice: { key: 'ERP_HdrGenerateInvoice', defaultText: 'Generate Invoice' },
        ERP_HdrWelcomeMessage: { key: 'ERP_HdrWelcomeMessage', defaultText: '' },
        ERP_HdrRecordSponsorShipCancellationRequest: { key: 'ERP_HdrRecordSponsorShipCancellationRequest', defaultText: 'Record SponsorShip cancellation request' },
        ERP_HdrInvoiceList: { key: 'ERP_HdrInvoiceList', defaultText: 'Invoice List' },
        ERP_HdrViewOrder: { key: 'ERP_HdrViewOrder', defaultText: 'View Order' },
        ERP_HdrRemarksOrder: { key: 'ERP_HdrRemarksOrder', defaultText: 'Remarks Order' },
        ERP_HdrDonationDetails: { key: 'ERP_HdrDonationDetails', defaultText: 'Donation Details' },
        ERP_HdrOrphanNew: { key: 'ERP_HdrOrphanNew', defaultText: 'Orphan New' },
        ERP_HdrOrphanRenewed: { key: 'ERP_HdrOrphanRenewed', defaultText: 'Orphan Renewed' },
        ERP_HdrOprhanEnded: { key: 'ERP_HdrOprhanEnded', defaultText: 'Oprhan Ended' },
        ERP_HdrTransferPointParticipants: { key: 'ERP_HdrTransferPointParticipants', defaultText: 'Transfer Point Participants' },
        ERP_HdrChangePassword: { key: 'ERP_HdrChangePassword', defaultText: 'Change Password' },
        ERP_HdrUpdateProfile: { key: 'ERP_HdrUpdateProfile', defaultText: 'Update Profile' },
        ERP_HdrProfile: { key: 'ERP_HdrProfile', defaultText: 'Profile' },
        ERP_HdrManageBalanceAmount: { key: 'ERP_HdrManageBalanceAmount', defaultText: 'Manage Balance Amount' },

        //#endregion


        //#region  Labels 
        ERP_LblEquivalentCurrencyAndAmount: { key: 'ERP_LblEquivalentCurrencyAndAmount', defaultText: 'Equivalent Currency & Amount' },
        ERP_LblSelectedPaymentsTotal: { key: 'ERP_LblSelectedPaymentsTotal', defaultText: 'Selected Payments Total' },
        ERP_LblAcknowledgeTransfer: { key: 'ERP_LblAcknowledgeTransfer', defaultText: 'Acknowledge Transfer' },
        ERP_LblDestination: { key: 'ERP_LblDestination', defaultText: 'Destination' },
        ERP_LblDestinationType: { key: 'ERP_LblDestinationType', defaultText: 'Destination Type' },
        ERP_LblLandingType: { key: 'ERP_LblLandingType', defaultText: 'Landing Type' },
        ERP_LblTrackingNumber: { key: "ERP_LblTrackingNumber", defaultText: 'Tracking Number' },
        ERP_LblTransferDate: { key: "ERP_LblTransferDate", defaultText: 'Transfer Date' },
        ERP_LblFilter: { key: "ERP_LblFilter", defaultText: 'Filter' },
        ERP_LblEdit: { key: 'ERP_LblEdit', defaultText: 'Edit' },
        ERP_LblDelete: { key: 'ERP_LblDelete', defaultText: 'Delete' },
        ERP_LblDetailView: { key: 'ERP_LblDetailView', defaultText: 'Detail View' },
        ERP_LblInvoiceGenerator: { key: 'ERP_LblInvoiceGenerator', defaultText: 'Invoice Generator' },
        ERP_LblViewHistory: { key: 'ERP_LblViewHistory', defaultText: 'View History' },
        ERP_LblViewDetails: { key: "ERP_LblViewDetails", defaultText: 'View Details' },
        ERP_LblSave: { key: 'ERP_LblSave', defaultText: 'Save' },
        ERP_LblCancel: { key: 'ERP_LblCancel', defaultText: 'Cancel' },
        ERP_LblActions: { key: 'ERP_LblActions', defaultText: 'Actions' },
        ERP_LblAction: { key: 'ERP_LblAction', defaultText: 'Action' },
        ERP_LblDownloadCSV: { key: 'ERP_LblDownloadCSV', defaultText: 'Download CSV' },
        ERP_LblPrevious: { key: 'ERP_LblPrevious', defaultText: 'Previous' },
        ERP_LblNext: { key: 'ERP_LblNext', defaultText: 'Next' },
        ERP_LblDispatch: { key: 'ERP_LblDispatch', defaultText: 'Dispatch' },
        ERP_LblUpdateCampaign: { key: 'ERP_LblUpdateCampaign', defaultText: 'Update Campaign' },
        ERP_LblCreateCashOut: { key: 'ERP_LblCreateCashOut', defaultText: 'Create Cash Out' },
        ERP_LblCurrencyCode: { key: 'ERP_LblCurrencyCode', defaultText: 'Currency Code' },
        ERP_LblCurrencyRate: { key: 'ERP_LblCurrencyRate', defaultText: 'Currency Rate' },
        ERP_LblForm: { key: 'ERP_LblForm', defaultText: 'Form' },
        ERP_LblEditOrder: { key: 'ERP_LblEditOrder', defaultText: 'Edit Order' },
        ERP_LblNewOrder: { key: 'ERP_LblNewOrder', defaultText: 'New Order' },
        ERP_LblEditTransfer: { key: 'ERP_LblEditTransfer', defaultText: 'Edit Transfer' },
        ERP_LblNewTransfer: { key: 'ERP_LblNewTransfer', defaultText: 'New Transfer' },
        ERP_LblSpecialService: { key: 'ERP_LblSpecialService', defaultText: 'Special Service' },
        ERP_LblEnded: { key: 'ERP_LblEnded', defaultText: 'Ended' },
        ERP_LblRenewal: { key: 'ERP_LblRenewal', defaultText: 'Renewal' },
        ERP_LblNew: { key: 'ERP_LblNew', defaultText: 'New' },
        ERP_LblCreatedOn: { key: 'ERP_LblCreatedOn', defaultText: 'Created On' },
        ERP_LblMarkedDoneOn: { key: 'ERP_LblMarkedDoneOn', defaultText: 'Marked Done On' },
        ERP_LblCreatorUserId: { key: 'ERP_LblCreatorUserId', defaultText: 'Created By' },
        ERP_LblMarkedDoneBy: { key: 'ERP_LblMarkedDoneBy', defaultText: 'Marked Done By' },
        ERP_LblLastModificationTime: { key: 'ERP_LblLastModificationTime', defaultText: 'Last Modified On' },
        ERP_LblLastModifierUserId: { key: 'ERP_LblLastModifierUserId', defaultText: 'Last Modified By' },
        ERP_LblType: { key: 'ERP_LblType', defaultText: 'Type' },
        ERP_LblSecureEntity: { key: 'ERP_LblSecureEntity', defaultText: 'Secure Entity' },
        ERP_LblIsSecured: { key: 'ERP_LblIsSecured', defaultText: 'Restrict Access' },
        ERP_LblSelectOriginType: { key: 'ERP_LblSelectOriginType', defaultText: 'Select Origin Type' },
        ERP_LblSelectDestinationType: { key: 'ERP_LblSelectDestinationType', defaultText: 'Select Destination Type' },
        ERP_LblSelectOrigin: { key: 'ERP_LblSelectOrigin', defaultText: 'Select Origin' },
        ERP_LblSelectDestination: { key: 'ERP_LblSelectDestination', defaultText: 'Select Destination' },
        ERP_LblUserName: { key: 'ERP_LblUserName', defaultText: 'User Name' },
        ERP_LblFullName: { key: 'ERP_LblFullName', defaultText: 'Full Name' },
        ERP_LblEmailAddress: { key: 'ERP_LblEmailAddress', defaultText: 'Email Address' },
        ERP_LblPassword: { key: 'ERP_LblPassword', defaultText: 'Password' },
        ERP_LblConfirmPassword: { key: 'ERP_LblConfirmPassword', defaultText: 'Confirm Password' },
        ERP_LblIsActive: { key: 'ERP_LblIsActive', defaultText: 'Is Active' },
        ERP_LblIsDelete: { key: 'ERP_LblIsDelete', defaultText: 'Is Delete' },
        ERP_LblIsDeleted: { key: 'ERP_LblIsDeleted', defaultText: 'Deleted' },
        ERP_LblIsSupporterNameRequired: { key: 'ERP_LblIsSupporterNameRequired', defaultText: 'Supporter Name Required' },
        ERP_LblRoles: { key: 'ERP_LblRoles', defaultText: 'Roles' },
        ERP_LblDonorNameArabic: { key: 'ERP_LblDonorNameArabic', defaultText: 'Donor Name Arabic' },
        ERP_LblDonorPhoneNumber: { key: 'ERP_LblDonorPhoneNumber', defaultText: 'Donor Phone Number' },
        ERP_LblDonorEmailAddress: { key: 'ERP_LblDonorEmailAddress', defaultText: 'Donor Email Address' },
        ERP_LblDonorCountry: { key: 'ERP_LblDonorCountry', defaultText: 'Donor Country' },
        ERP_LblOrphanName: { key: 'ERP_LblOrphanName', defaultText: 'Orphan Name' },
        ERP_LblRepLanguage: { key: 'ERP_LblRepLanguage', defaultText: 'Rep Language' },
        ERP_LblUserNameOrEmail: { key: 'ERP_LblUserNameOrEmail', defaultText: 'User Name Or Email' },
        ERP_LblRememberMe: { key: 'ERP_LblRememberMe', defaultText: 'Remember Me' },
        ERP_LblForgotPassword: { key: 'ERP_LblForgotPassword', defaultText: 'Forgot Password' },
        ERP_LblDate: { key: 'ERP_LblDate', defaultText: 'Date' },
        ERP_LblStartDate: { key: 'ERP_LblStartDate', defaultText: 'Start Date' },
        ERP_LblEndDate: { key: 'ERP_LblEndDate', defaultText: 'End Date' },
        ERP_LblProduct: { key: 'ERP_LblProduct', defaultText: 'Product' },
        ERP_LblCategory: { key: 'ERP_LblCategory', defaultText: 'Category' },
        ERP_LblCampaign: { key: 'ERP_LblCampaign', defaultText: 'Campaign' },
        ERP_LblCampaignNotification: { key: 'ERP_LblCampaignNotification', defaultText: 'Campaign (The notification will be sent to all participants of selected campaign)' },
        ERP_LblSupporter: { key: 'ERP_LblSupporter', defaultText: 'Supporter' },
        ERP_LblIcManager: { key: 'ERP_LblIcManager', defaultText: 'IC/IC Manager' },
        ERP_LblTargetAssigned: { key: 'ERP_LblTargetAssigned', defaultText: 'Target Assigned' },
        ERP_LblRemainingTarget: { key: 'ERP_LblRemainingTarget', defaultText: 'Remaining Target' },
        ERP_LblTargetAchievedPercentage: { key: 'ERP_LblTargetAchievedPercentage', defaultText: 'Target Achieved (%)' },
        ERP_LblUser: { key: 'ERP_LblUser', defaultText: 'User' },
        ERP_LblAmount: { key: 'ERP_LblAmount', defaultText: 'Amount' },
        ERP_LblSymbol: { key: 'ERP_LblSymbol', defaultText: 'Symbol' },
        ERP_LblRate: { key: 'ERP_LblRate', defaultText: 'Rate' },
        ERP_LblIconUrl: { key: 'ERP_LblIconUrl', defaultText: 'Icon Url' },
        ERP_LblOrderStatus: { key: 'ERP_LblOrderStatus', defaultText: 'Order Status' },
        ERP_LblCode: { key: 'ERP_LblCode', defaultText: 'Code' },
        ERP_LblInternalName: { key: 'ERP_LblInternalName', defaultText: 'Internal Name' },
        ERP_LblExternalName: { key: 'ERP_LblExternalName', defaultText: 'External Name' },
        ERP_LblSearchByCode: { key: 'ERP_LblSearchByCode', defaultText: 'Search By Code' },
        ERP_LblSearchByType: { key: 'ERP_LblSearchByType', defaultText: 'Search By Type' },
        ERP_LblDigitalCode: { key: 'ERP_LblDigitalCode', defaultText: 'Digital Code' },
        ERP_LblTransferPointType: { key: 'ERP_LblTransferPointType', defaultText: 'Transfer Point Type' },
        ERP_LblTransferPointName: { key: 'ERP_LblTransferPointName', defaultText: 'Transfer Point Name' },
        ERP_LblBalanceAmounts: { key: 'ERP_LblBalanceAmounts', defaultText: 'Balance Amounts' },
        ERP_LblIsProductActive: { key: 'ERP_LblIsProductActive', defaultText: 'Is Product Active' },
        ERP_LblOrigin: { key: 'ERP_LblOrigin', defaultText: 'Origin' },
        ERP_LblTransferContents: { key: 'ERP_LblTransferContents', defaultText: 'Transfer Contents' },
        ERP_LblStatus: { key: 'ERP_LblStatus', defaultText: 'Status' },
        ERP_LblAcknowlegedBy: { key: 'ERP_LblAcknowlegedBy', defaultText: 'Acknowledged By' },
        ERP_LblAcknowledgedDate: { key: 'ERP_LblAcknowledgedDate', defaultText: 'Acknowledged Date' },
        ERP_LblName: { key: 'ERP_LblName', defaultText: 'Name' },
        ERP_LblSurname: { key: 'ERP_LblSurname', defaultText: 'Surname' },
        ERP_LblDescription: { key: 'ERP_LblDescription', defaultText: 'Description' },
        ERP_LblTarget: { key: 'ERP_LblTarget', defaultText: 'Target' },
        ERP_LblCreate: { key: 'ERP_LblCreate', defaultText: 'Create' },
        ERP_LblChangeLanguage: { key: 'ERP_LblChangeLanguage', defaultText: 'Change Language' },
        ERP_LblSelectMonth_Year: { key: 'ERP_LblSelectMonth_Year', defaultText: 'Select Month/Year' },
        ERP_LblNameOnReceipt: { key: 'ERP_LblNameOnReceipt', defaultText: 'Name On Receipt' },
        ERP_LblDonorContactNumber: { key: 'ERP_LblDonorContactNumber', defaultText: 'Donor Contact Number' },
        ERP_LblDonor: { key: 'ERP_LblDonor', defaultText: 'Donor' },
        ERP_LblDonorName: { key: 'ERP_LblDonorName', defaultText: 'Donor Name' },
        ERP_LblCurrency: { key: 'ERP_LblCurrency', defaultText: 'Currency' },
        ERP_LblExchange: { key: 'ERP_LblExchange', defaultText: 'Exchange' },
        ERP_LblOrphanId: { key: 'ERP_LblOrphanId', defaultText: 'Orphan Id' },
        ERP_LblOrphanIds: { key: 'ERP_LblOrphanIds', defaultText: 'Orphan Ids' },
        ERP_LblRepName: { key: 'ERP_LblRepName', defaultText: 'Rep Name' },
        ERP_LblOrderDate: { key: 'ERP_LblOrderDate', defaultText: 'Order Date' },
        ERP_LblYes: { key: 'ERP_LblYes', defaultText: 'Yes' },
        ERP_LblNo: { key: 'ERP_LblNo', defaultText: 'No' },
        ERP_LblClose: { key: 'ERP_LblClose', defaultText: 'Close' },
        ERP_LblParticipants: { key: 'ERP_LblParticipants', defaultText: 'Participants' },
        ERP_LblLogout: { key: 'ERP_LblLogout', defaultText: 'Logout' },
        ERP_LblLoginFailed: { key: 'ERP_LblLoginFailed', defaultText: 'Login Failed' },
        ERP_LblMyTarget: { key: 'ERP_LblMyTarget', defaultText: 'MyTarget' },
        ERP_LblAdditionalTarget: { key: 'ERP_LblAdditionalTarget', defaultText: 'Additional Target' },
        ERP_LblAdditionalInfo: { key: 'ERP_LblAdditionalInfo', defaultText: 'Additional Info' },
        ERP_LblAdditionalNote: { key: 'ERP_LblAdditionalNote', defaultText: 'Additional Note' },
        ERP_LblTargetAchieved: { key: 'ERP_LblTargetAchieved', defaultText: 'Target Achieved' },
        ERP_LblIsTargetAchieved: { key: 'ERP_LblIsTargetAchieved', defaultText: 'Is Target Achieved' },
        ERP_LblConsecutiveRecordCTAText: { key: 'ERP_LblConsecutiveRecordCTAText', defaultText: 'Consecutive Record CTA Text' },
        ERP_LblFirstRecordCTAText: { key: 'ERP_LblFirstRecordCTAText', defaultText: 'First Record CTA Text' },
        ERP_LblCampaignName: { key: 'ERP_LblCampaignName', defaultText: 'Campaign Name' },
        ERP_LblCountryName: { key: 'ERP_LblCountryName', defaultText: 'Country Name' },
        ERP_LblHtmlTemplateName: { key: 'ERP_LblHtmlTemplateName', defaultText: 'Html Template Name' },
        ERP_LblHtmlTemplateCode: { key: 'ERP_LblHtmlTemplateCode', defaultText: 'Html Template Code' },
        ERP_LblHtmlTemplateType: { key: 'ERP_LblHtmlTemplateCode', defaultText: 'Html Template Type' },
        ERP_LblHtmlTemplateContent: { key: 'ERP_LblHtmlTemplateContent', defaultText: 'Html Template Content' },
        ERP_LblLatitude: { key: 'ERP_LblLatitude', defaultText: 'Latitude' },
        ERP_LblLongitude: { key: 'ERP_LblLongitude', defaultText: 'Longitude' },
        ERP_LblCreationTime: { key: 'ERP_LblCreationTime', defaultText: 'Creation Time' },
        ERP_LblOrderCreationDate: { key: 'ERP_LblOrderCreationDate', defaultText: 'Order Creation Date' },
        ERP_LblCreationDate: { key: 'ERP_LblCreationDate', defaultText: 'Creation Date' },
        ERP_LblWhenToPerform: { key: 'ERP_LblWhenToPerform', defaultText: 'When To Perform' },
        ERP_LblPerformedDate: { key: 'ERP_LblPerformedDate', defaultText: 'Performed Date' },
        ERP_LblCountryCode: { key: 'ERP_LblCountryCode', defaultText: 'Country Code' },
        ERP_LblTranslations: { key: 'ERP_LblTranslations', defaultText: 'Translations' },
        ERP_LblProductName: { key: 'ERP_LblProductName', defaultText: 'Product Name' },
        ERP_LblUnitNameSingular: { key: 'ERP_LblUnitNameSingular', defaultText: 'Unit Name Singular' },
        ERP_LblUnitNamePlural: { key: 'ERP_LblUnitNamePlural', defaultText: 'Unit Name Plural' },
        ERP_LblUnitName: { key: 'ERP_LblUnitName', defaultText: 'Unit Name' },
        ERP_LblDiscard: { key: 'ERP_LblDiscard', defaultText: 'Discard' },
        ERP_LblProgram: { key: 'ERP_LblProgram', defaultText: 'Program' },
        ERP_LblIsAllowedAdditionalTargetAchieved: { key: 'ERP_LblIsAllowedAdditionalTargetAchieved', defaultText: 'Is Allowed Additional Target Achieved' },
        ERP_LblAcceptDonationAfterTargetAchieved: { key: 'ERP_LblAcceptDonationAfterTargetAchieved', defaultText: 'Accept Donation After Target Achieved' },
        ERP_LblDisplayOrder: { key: 'ERP_LblDisplayOrder', defaultText: 'Display Order' },
        ERP_LblComment: { key: 'ERP_LblComment', defaultText: 'Comment' },
        ERP_LblComments: { key: 'ERP_LblComments', defaultText: 'Comments' },
        ERP_LblRemarks: { key: 'ERP_LblRemarks', defaultText: 'Remarks' },
        ERP_LblLockDonationAfterTargetAchieved: { key: 'ERP_LblLockDonationAfterTargetAchieved', defaultText: 'Lock Donation After Target Achieved' },
        ERP_LblIsMainCampaign: { key: 'ERP_LblIsMainCampaign', defaultText: 'Main Campaign' },
        ERP_LblIsCampaignParticipants: { key: 'ERP_LblIsCampaignParticipants', defaultText: 'Campaign Participants' },
        ERP_LblCountry: { key: 'ERP_LblCountry', defaultText: 'Country' },
        ERP_LblLogIn: { key: 'ERP_LblLogIn', defaultText: 'Log In' },
        ERP_LblContactNumber: { key: 'ERP_LblContactNumber', defaultText: 'Contact Number' },
        ERP_LblGender: { key: 'ERP_LblGender', defaultText: 'Gender' },
        ERP_LblDateOfBirth: { key: 'ERP_LblDateOfBirth', defaultText: 'Date Of Birth' },
        ERP_LblMale: { key: 'ERP_LblMale', defaultText: 'Male' },
        ERP_LblFemale: { key: 'ERP_LblFemale', defaultText: 'Female' },
        ERP_LblCurrentPassword: { key: 'ERP_LblCurrentPassword', defaultText: 'Current Password' },
        ERP_LblNewPassword: { key: 'ERP_LblNewPassword', defaultText: 'New Password' },
        ERP_LblOTP: { key: 'ERP_LblOTP', defaultText: 'OTP' },
        ERP_LblId: { key: 'ERP_LblId', defaultText: 'Id' },
        ERP_LblBackToLogin: { key: 'ERP_LblBackToLogin', defaultText: 'Back to Login' },
        ERP_LblSearchByProduct: { key: 'ERP_LblSearchByProduct', defaultText: 'Search By Product' },
        ERP_LblSearchByCampaign: { key: 'ERP_LblSearchByCampaign', defaultText: 'Search By Campaign' },
        ERP_LblSearchByCountry: { key: 'ERP_LblSearchByCountry', defaultText: 'Search By Country' },
        ERP_LblSearchByOrderStatus: { key: 'ERP_LblSearchByOrderStatus', defaultText: 'Search By Order Status' },
        ERP_LblSearchByRep: { key: 'ERP_LblSearchByRep', defaultText: 'Search By Rep' },
        ERP_LblSearchByName: { key: 'ERP_LblSearchByName', defaultText: 'Search By Name' },
        ERP_LblSupporterType: { key: 'ERP_LblSupporterType', defaultText: 'Supporter Type' },
        ERP_LblProductCode: { key: 'ERP_LblProductCode', defaultText: 'Product Code' },
        ERP_LblOrderNumber: { key: 'ERP_LblOrderNumber', defaultText: 'Order Number' },
        ERP_LblIsPartialPaymentAllowed: { key: 'ERP_LblIsPartialPaymentAllowed', defaultText: 'Is Partial Payment Allowed' },
        ERP_LblPartialTransferManagement: { key: 'ERP_LblPartialTransferManagement', defaultText: 'Partial Transfer Management' },
        ERP_LblPartialTransfer: { key: 'ERP_LblPartialTransfer', defaultText: 'Partial Transfer' },
        ERP_LblSupporterLanguage: { key: 'ERP_LblSupporterLanguage', defaultText: 'Supporter Language' },
        ERP_LblSupporterCode: { key: 'ERP_LblSupporterCode', defaultText: 'Supporter Code' },
        ERP_LblIsFeatured: { key: 'ERP_LblIsFeatured', defaultText: 'Is Featured' },
        ERP_LblSearchByProgramCategory: { key: 'ERP_LblSearchByProgramCategory', defaultText: 'Search By Program Category' },
        ERP_LblSearchByProgram: { key: 'ERP_LblSearchByProgram', defaultText: 'Search By Program' },
        ERP_LblSearchByProductForm: { key: 'ERP_LblSearchByProductForm', defaultText: 'Search By Product Form' },
        ERP_LblParentProgram: { key: 'ERP_LblParentProgram', defaultText: 'Parent Program' },
        ERP_LblHierarchyLevel: { key: 'ERP_LblHierarchyLevel', defaultText: 'Hierarchy Level' },
        ERP_LblFormFields: { key: 'ERP_LblFormFields', defaultText: 'Form Fields' },
        ERP_LblSearchByCurrency: { key: 'ERP_LblSearchByCurrency', defaultText: 'Search By Currency' },
        ERP_LblIsAllowedInCampaign: { key: 'ERP_LblIsAllowedInCampaign', defaultText: 'Is Allowed In Campaign' },
        ERP_LblSearchByStatus: { key: 'ERP_LblSearchByStatus', defaultText: 'Search By Status' },
        ERP_LblSearchByDestination: { key: 'ERP_LblSearchByDestination', defaultText: 'Search By Destination' },
        ERP_LblSearchByOrigin: { key: 'ERP_LblSearchByOrigin', defaultText: 'Search By Origin' },
        ERP_LblAccessMembers: { key: 'ERP_LblAccessMembers', defaultText: 'Access Members' },
        ERP_LblAccessCountries: { key: 'ERP_LblAccessCountries', defaultText: 'Access Countries' },
        ERP_LblAcknowledgeMembers: { key: 'ERP_LblAcknowledgeMembers', defaultText: 'Acknowledge Members' },
        ERP_LblCustomField: { key: 'ERP_LblCustomField', defaultText: 'Custom Field JSON' },
        ERP_LblQuantity: { key: 'ERP_LblQuantity', defaultText: 'Quantity' },
        ERP_LblTotalCount: { key: 'ERP_LblTotalCount', defaultText: 'Total Records' },
        ERP_LblProgramCategory: { key: 'ERP_LblProgramCategory', defaultText: 'Program Category' },
        ERP_LblProductForms: { key: 'ERP_LblProductForms', defaultText: 'Product Forms' },
        ERP_LblProductForm: { key: 'ERP_LblProductForm', defaultText: 'Product Form' },
        ERP_LblHTMLTemplates: { key: 'ERP_LblHTMLTemplates', defaultText: 'HTML Templates' },
        ERP_LblHTMLTemplate: { key: 'ERP_LblHTMLTemplate', defaultText: 'HTML Template' },
        ERP_LblTransferPoints: { key: 'ERP_LblTransferPoints', defaultText: 'Transfer Points' },
        ERP_LblTransferPoint: { key: 'ERP_LblTransferPoint', defaultText: 'Transfer Point' },
        ERP_LblUserSettings: { key: 'ERP_LblUserSettings', defaultText: 'User Settings' },
        ERP_LblAppSettings: { key: 'ERP_LblAppSettings', defaultText: 'App Settings' },
        ERP_LblApp: { key: 'ERP_LblApp', defaultText: 'App' },
        ERP_LblDeadline: { key: 'ERP_LblDeadline', defaultText: 'Deadline' },
        ERP_LblMarjaeName: { key: 'ERP_LblMarjaeName', defaultText: 'Marjae Name' },
        ERP_LblSahmType: { key: 'ERP_LblSahmType', defaultText: 'Sahm Type' },
        ERP_LblReceiptRequired: { key: 'ERP_LblReceiptRequired', defaultText: 'Receipt Required' },
        ERP_LblNameOnMarjaReceipt: { key: 'ERP_LblNameOnMarjaReceipt', defaultText: 'Name on Marja Receipt' },
        ERP_LblSearchByApp: { key: 'ERP_LblSearchByApp', defaultText: 'Search By App' },
        ERP_LblSelectApp: { key: 'ERP_LblSelectApp', defaultText: 'Please Select App' },
        ERP_LblSaveAppUpdate: { key: 'ERP_LblSaveAppUpdate', defaultText: 'Save App Update' },
        ERP_LblClearPermission: { key: 'ERP_LblClearPermission', defaultText: 'Clear Permission' },
        ERP_LblClearAllCache: { key: 'ERP_LblClearAllCache', defaultText: 'Clear All Cache' },
        ERP_LblPermissions: { key: 'ERP_LblPermissions', defaultText: 'Permissions' },
        ERP_LblUsers: { key: 'ERP_LblUsers', defaultText: 'Users' },
        ERP_LblAllContent: { key: 'ERP_LblAllContent', defaultText: 'All Content' },
        ERP_LblViewBalanceAmounts: { key: 'ERP_LblViewBalanceAmounts', defaultText: 'View Balance Amounts' },
        ERP_LblRemarksOrder: { key: 'ERP_LblRemarksOrder', defaultText: 'Remarks Order' },
        ERP_LblMarkAsDone: { key: 'ERP_LblMarkAsDone', defaultText: 'Mark as Done' },
        ERP_LblTitle: { key: 'ERP_LblTitle', defaultText: 'Title' },
        ERP_LblMessage: { key: 'ERP_LblMessage', defaultText: 'Message' },
        ERP_LblSendImmediately: { key: 'ERP_LblSendImmediately', defaultText: 'Send Immediately' },
        ERP_LblSendToCampaignParticipantsOnly: { key: 'ERP_LblSendToCampaignParticipantsOnly', defaultText: 'Send to campaign participants only?' },
        ERP_LblSelectCampaign: { key: 'ERP_LblSelectCampaign', defaultText: 'Select Campaign' },
        ERP_LblNotificationRecipients: { key: 'ERP_LblNotificationRecipients', defaultText: 'Select Recipients' },
        ERP_LblSelectRecipients: { key: 'ERP_LblSelectRecipients', defaultText: 'This push notification will be sent to all Akhyar App users. If you want to send to specific users only, please select the users below (otherwise leave the field empty to send to all Akhyar App users)' },
        ERP_LblSelectUpdateType: { key: 'ERP_LblSelectUpdateType', defaultText: 'Select Update Type' },
        ERP_LblAchievedCount: { key: 'ERP_LblAchievedCount', defaultText: 'Sum of Items' },
        ERP_LblCountryRep: { key: 'ERP_LblCountryRep', defaultText: 'Country / Rep' },
        ERP_LblOriginalCurrency: { key: 'ERP_LblOriginalCurrency', defaultText: 'Original Currency' },
        ERP_LblOriginalAmount: { key: 'ERP_LblOriginalAmount', defaultText: 'Original Amount' },
        ERP_LblFXRate: { key: 'ERP_LblFXRate', defaultText: 'FX Rate' },
        ERP_LblEquivalentCurrency: { key: 'ERP_LblEquivalentCurrency', defaultText: 'Equivalent Currency' },
        ERP_LblEquivalentAmount: { key: 'ERP_LblEquivalentAmount', defaultText: 'Equivalent Amount' },
        ERP_LblRefrenceOrInvoiceId: { key: 'ERP_LblRefrenceOrInvoiceId', defaultText: 'Reference ID | Invoice ID' },
        ERP_LblPersonName: { key: 'ERP_LblPersonName', defaultText: 'Person Name' },
        ERP_LblPersonWhatsApp: { key: 'ERP_LblPersonWhatsApp', defaultText: 'Person WhatsApp' },
        ERP_LblAttachment: { key: 'ERP_LblAttachment', defaultText: 'Attachment' },
        ERP_LblUsdPrice: { key: 'ERP_LblUsdPrice', defaultText: 'USD Price' },
        ERP_LblDateOfTransfer: { key: "ERP_LblDateOfTransfer", defaultText: 'Date of Transfer' },
        ERP_LblNoOfOrphans: { key: 'ERP_LblNoOfOrphans', defaultText: 'No. of Orphans' },
        ERP_LblAppName: { key: 'ERP_LblAppName', defaultText: 'App Name' },
        ERP_LblPushNotificationTitle: { key: 'ERP_LblPushNotificationTitle', defaultText: 'Push Notification Title' },
        ERP_LblCampaignAppUpdateTitle: { key: 'ERP_LblCampaignAppUpdateTitle', defaultText: 'Campaign App Update Title' },



        ERP_LblOrderNum: { key: 'ERP_LblOrderNum', defaultText: 'Order #' },
        ERP_LblDateOfRequest: { key: 'ERP_LblDateOfRequest', defaultText: 'Date Of Request' },
        ERP_LblOrderCreationTime: { key: 'ERP_LblOrderCreationTime', defaultText: 'Order Creation Time' },
        ERP_LblProgramName: { key: 'ERP_LblProgramName', defaultText: 'Program Name' },
        ERP_LblOccasion: { key: 'ERP_LblOccasion', defaultText: 'Occasion' },
        ERP_LblOtherOccasion: { key: 'ERP_LblOtherOccasion', defaultText: 'Other Occasion' },
        ERP_LblZiyara: { key: 'ERP_LblZiyara', defaultText: 'Ziyara' },
        ERP_LblMarhumName: { key: 'ERP_LblMarhumName', defaultText: 'Marhum Name' },
        ERP_LblChildName: { key: 'ERP_LblChildName', defaultText: 'Child Name' },
        ERP_LblFitrahType: { key: 'ERP_LblFitrahType', defaultText: 'Fitrah Type' },
        ERP_LblFitrahDonorCountry: { key: 'ERP_LblFitrahDonorCountry', defaultText: 'Fitrah (Donor Country)' },
        ERP_LblDateOfExecution: { key: 'ERP_LblDateOfExecution', defaultText: 'Date of Execution' },
        ERP_LblCity: { key: 'ERP_LblCity', defaultText: 'City' },
        ERP_LblHolyShrine: { key: 'ERP_LblHolyShrine', defaultText: 'Holy Shrine' },
        ERP_LblOrphanType: { key: 'ERP_LblOrphanType', defaultText: 'Orphan Type' },
        ERP_LblOrphanID: { key: 'ERP_LblOrphanID', defaultText: 'Orphan ID' },
        ERP_LblUnitAmount: { key: 'ERP_LblUnitAmount', defaultText: 'Unit Amount' },
        ERP_LblTotalAmount: { key: 'ERP_LblTotalAmount', defaultText: 'Total Amount' },
        ERP_LblAdditionalComments: { key: 'ERP_LblAdditionalComments', defaultText: 'Additional Comments' },
        ERP_LblIC: { key: 'ERP_LblIC', defaultText: 'IC' },
        ERP_LblHolyPersonality: { key: 'ERP_LblHolyPersonality', defaultText: 'Holy Personality' },





        //#endregion

        //#region  Messgaes 
        ERP_MsgConfirmTransferEdit: { key: "ERP_MsgConfirmTransferEdit", defaultText: 'Are you sure you want to edit the transfer ? ' },
        ERP_MsgConfirmTransferDiscard: { key: "ERP_MsgConfirmTransferDiscard", defaultText: 'Are you sure to Discard any changes made ?' },
        ERP_MsgConfirmOperation: { key: "ERP_MsgConfirmOperation", defaultText: 'Are you sure you want to perform the action ? ' },
        ERP_MsgConfirmDeleteRecord: { key: "ERP_MsgConfirmDeleteRecord", defaultText: 'Are you sure you want to delete the record ?' },
        ERP_MsgConfirmCompletedOrder: { key: "ERP_MsgConfirmCompletedOrder", defaultText: 'Are you sure you have completed order ?' },
        ERP_MsgPleaseEnterAmountForAtLeastOneCashOut: { key: "ERP_MsgPleaseEnterAmountForAtLeastOneCashOut", defaultText: 'Please enter amount for atLeast one cash out' },
        ERP_MsgPleaseSelectADonation: { key: 'ERP_MsgPleaseSelectADonation', defaultText: 'Please Select a Donation' },
        ERP_MsgConfirmAcknowledgePaymentTransfer: { key: 'ERP_MsgConfirmAcknowledgePaymentTransfer', defaultText: 'Confirm Acknowledge Payment Transfer' },
        ERP_MsgErrorUnknownError: { key: 'ERP_MsgErrorUnknownError', defaultText: 'Unknown Error' },
        ERP_MsgResetPasswordNote: { key: 'ERP_MsgResetPasswordNote', defaultText: 'Your old password will be discarded and you will be sent an OTP verification code on your email to reset your password' },
        ERP_MsgPasswordChangedSuccessfully: { key: 'ERP_MsgPasswordChangedSuccessfully', defaultText: 'password changed successfully' },
        ERP_MsgSuccessfulRecordSave: { key: 'ERP_MsgSuccessfulRecordSave', defaultText: 'Record has been saved successfully!' },
        ERP_MsgSuccessfulRecordUpdate: { key: 'ERP_MsgSuccessfulRecordUpdate', defaultText: 'Record has been updated successfully!' },
        ERP_MsgTransferAckonwledgedSuccessfully: { key: 'ERP_MsgTransferAckonwledgedSuccessfully', defaultText: 'Transfer ackonwledged successfully!' },
        ERP_MsgRequestedOperationFailed: { key: 'ERP_MsgRequestedOperationFailed', defaultText: 'Something went wrong, please try again.' },
        ERP_MsgAllMembersReps: { key: 'ERP_MsgAllMembersReps', defaultText: 'will be visible to all members/reps' },
        ERP_MsgAccessMembersReps: { key: 'ERP_MsgAccessMembersReps', defaultText: 'will be visible to only below access members/reps' },
        ERP_MsgMembersPermission: { key: 'ERP_MsgMembersPermission', defaultText: 'Below members will have permission to acknowledge transfers for' },
        ERP_MsgAkhyarAppUpdateNonCampaignNote: { key: 'ERP_MsgAkhyarAppUpdateNonCampaignNote', defaultText: 'Push notification will be sent to all users immediately if "Send Immediately" is checked. Otherwise, it will be sent based on regular schedule. ' },
        ERP_MsgAkhyarAppUpdateCampaignNote: { key: 'ERP_MsgAkhyarAppUpdateCampaignNote', defaultText: 'Push notification will be sent to all users participating in selected campaign immediately if "Send Immediately" is checked. Otherwise, it will be sent based on regular schedule.' },

        ERP_MsgFinalizeExchnageRows: { key: 'ERP_MsgFinalizeExchnageRows', defaultText: 'Please Finalize Exchange Details' },
        ERP_MsgRequestedFailed: { key: 'ERP_MsgRequestedFailed', defaultText: 'Could not get data' },
        //#endregion

        //#region  Fields Error Messages 
        ERP_Error_FieldPleaseSelectOrigin: { key: 'ERP_Error_FieldPleaseSelectOrigin', defaultText: 'Please Select Origin' },
        ERP_Error_FieldPleaseSelectDestination: { key: 'ERP_Error_FieldPleaseSelectDestination', defaultText: 'Please Select Destination' },
        ERP_Error_FieldRecipients: { key: 'ERP_Error_FieldRecipients', defaultText: 'Please Select Recipient' },
        ERP_Error_FieldSelectOriginType: { key: 'ERP_Error_FieldSelectOriginType', defaultText: 'Please Select Origin Type' },
        ERP_Error_FieldSelectDestinationType: { key: 'ERP_Error_FieldSelectDestinationType', defaultText: 'Please Select Destination Type' },
        ERP_Error_FieldPleaseEnterAmount: { key: 'ERP_Error_FieldPleaseEnterAmount', defaultText: 'Please Enter Amount' },
        ERP_Error_FieldPleaseSelectCurrency: { key: 'ERP_Error_FieldPleaseSelectCurrency', defaultText: 'Please Select Currency' },
        ERP_Error_FieldPleaseEnterRate: { key: 'ERP_Error_FieldPleaseEnterRate', defaultText: 'Please Enter Rate' },
        ERP_Error_FieldThisFieldIsRequired: { key: 'ERP_Error_FieldThisFieldIsRequired', defaultText: 'This Field Is Required' },
        ERP_Error_FieldValidEmail: { key: 'ERP_Error_FieldValidEmail', defaultText: 'The input is not valid E-mail!' },
        ERP_Error_FieldPleaseEnterDonorName: { key: 'ERP_Error_FieldPleaseEnterDonorName', defaultText: 'Please Enter Donor Name' },
        ERP_Error_FieldPleaseEnterAddtionalTarget: { key: 'ERP_Error_FieldPleaseEnterAddtionalTarget', defaultText: 'Please enter Addtional Target' },
        ERP_Error_FieldPleaseEnterComment: { key: 'ERP_Error_FieldPleaseEnterComment', defaultText: 'Please enter comment' },
        ERP_Error_FieldPleaseEnterCampaignName: { key: 'ERP_Error_FieldPleaseEnterCampaignName', defaultText: 'Please Enter Campaign Name' },
        ERP_Error_FieldPleaseEnterDescription: { key: 'ERP_Error_FieldPleaseEnterDescription', defaultText: 'Please Enter Description' },
        ERP_Error_FieldPleaseEnterDisplayOrder: { key: 'ERP_Error_FieldPleaseEnterDisplayOrder', defaultText: 'Please Enter Display Order' },
        ERP_Error_FieldPleaseEnterTarget: { key: 'ERP_Error_FieldPleaseEnterTarget', defaultText: 'Please Enter Target' },
        ERP_Error_FieldPleaseSelectStartDate: { key: 'ERP_Error_FieldPleaseSelectStartDate', defaultText: 'Please Select Start Date' },
        ERP_Error_FieldPleaseSelectEndDate: { key: 'ERP_Error_FieldPleaseSelectEndDate', defaultText: 'Please Select End Date' },
        ERP_Error_FieldPleaseSelectProduct: { key: 'ERP_Error_FieldPleaseSelectProduct', defaultText: 'Please Select Product' },
        ERP_Error_FieldPleaseSelectCountry: { key: 'ERP_Error_FieldPleaseSelectCountry', defaultText: 'Please Select Country' },
        ERP_Error_FieldPleaseSelectCampaign: { key: 'ERP_Error_FieldPleaseSelectCampaign', defaultText: 'Please Select Campaign' },
        ERP_Error_FieldPleaseSelectService: { key: 'ERP_Error_FieldPleaseSelectService', defaultText: 'Please Select Service' },
        ERP_Error_FieldPleaseSelectForm: { key: 'ERP_Error_FieldPleaseSelectForm', defaultText: 'Please Select Form' },
        ERP_Error_FieldPleaseEnterOrderDate: { key: 'ERP_Error_FieldPleaseEnterOrderDate', defaultText: 'Please Enter Order Date' },
        ERP_Error_FieldPleaseSelectUser: { key: 'ERP_Error_FieldPleaseSelectUser', defaultText: 'Please Select User' },
        ERP_Error_FieldPleaseSelectSupporter: { key: 'ERP_Error_FieldPleaseSelectSupporter', defaultText: 'Please Select Supporter' },
        ERP_Error_FieldPleaseEnterCurrentPassword: { key: 'ERP_Error_FieldPleaseEnterCurrentPassword', defaultText: 'Please Enter Current Password' },
        ERP_Error_FieldPleaseEnterNewPassword: { key: 'ERP_Error_FieldPleaseEnterNewPassword', defaultText: 'Please Enter New Password' },
        ERP_Error_FieldPleaseEnterConfirmPassword: { key: 'ERP_Error_FieldPleaseEnterConfirmPassword', defaultText: 'Please Enter Confirm Password' },
        ERP_Error_FieldPleaseEnterName: { key: 'ERP_Error_FieldPleaseEnterName', defaultText: 'Please Enter Name' },
        ERP_Error_FieldPleaseEnterSurname: { key: 'ERP_Error_FieldPleaseEnterSurname', defaultText: 'Please Enter Surname' },
        ERP_Error_FieldPleaseEnterUserName: { key: 'ERP_Error_FieldPleaseEnterUserName', defaultText: 'Please Enter User Name' },
        ERP_Error_FieldPleaseEnterEmail: { key: 'ERP_Error_FieldPleaseEnterEmail', defaultText: 'Please Enter Email' },
        ERP_Error_FieldPleaseEnterPassword: { key: 'ERP_Error_FieldPleaseEnterPassword', defaultText: 'Please Enter Password' },
        ERP_Error_FieldPTwoPasswordsDoNotMatch: { key: 'ERP_Error_FieldPTwoPasswordsDoNotMatch', defaultText: 'Two passwords that you enter is inconsistent' },
        ERP_Error_FieldPleaseSelectAppUpdateType: { key: 'ERP_Error_FieldPleaseSelectAppUpdateType', defaultText: 'Please Select App Update type' },

        ERP_Error_FieldMinValueMessage: { key: 'ERP_Error_FieldMinValueMessage', defaultText: 'Value must be greater than or equal to' },
        ERP_Error_FieldMaxValueMessage: { key: 'ERP_Error_FieldMaxValueMessage', defaultText: 'Value must be less than or equal to' },
        ERP_Error_FieldValidContactNumber: { key: 'ERP_Error_FieldValidContactNumber', defaultText: 'Please enter a valid contact number' },

        ERP_Error_FieldOnly250charactersValueMessage: { key: 'ERP_Error_FieldOnly250charactersValueMessage', defaultText: 'Only 250 characters allowed' },
        ERP_Error_FieldOnly50charactersValueMessage: { key: 'ERP_Error_FieldOnly50charactersValueMessage', defaultText: 'Only 50 characters allowed' },
        ERP_Error_FieldPleaseEnterTitle: { key: 'ERP_Error_FieldPleaseEnterTitle', defaultText: 'Please Enter Title' },
        ERP_Error_FieldDonorCountry: { key: 'ERP_Error_FieldDonorCountry', defaultText: 'Not specified' },

        //#endregion

        // #Other

        ERP_BtnGenerate: { key: 'ERP_BtnGenerate', defaultText: 'Generate' },
        ERP_BtnGenrateAndDownload: { key: 'ERP_BtnGenrateAndDownload', defaultText: 'Genrate & Download' },
        ERP_AppName: { key: 'ERP_AppName', defaultText: 'App Name' },
        ERP_BtnSendEmail: { key: 'ERP_BtnSendEmail', defaultText: 'Send Email ' },
        ERP_BtnResetPassword: { key: 'ERP_BtnResetPassword', defaultText: 'Reset Password' },
        ERP_BtnManageTransferPointUsers: { key: 'ERP_BtnManageTransferPointUsers', defaultText: 'Manage Transfer Point Users' },
        ERP_BtnUpdateProfile: { key: 'ERP_BtnUpdateProfile', defaultText: 'Edit Profile' },
        ERP_BtnUpdatePassword: { key: 'ERP_BtnUpdatePassword', defaultText: 'Update Password' },
        ERP_BtnChangePassword: { key: 'ERP_BtnChangePassword', defaultText: 'Change Password' },
        ERP_BtnSend: { key: 'ERP_BtnSend', defaultText: 'Send' },

        // #Other




};
export default LocalizationKeys;