import LoadableComponent from './../Loadable/index';
import { UnorderedListOutlined, HomeOutlined, UserOutlined, ProfileOutlined, TagsOutlined, AppstoreOutlined, FundOutlined, CodeSandboxOutlined, ShoppingCartOutlined, TransactionOutlined, RetweetOutlined, AppstoreAddOutlined, ColumnWidthOutlined, LogoutOutlined, UsergroupDeleteOutlined, FileDoneOutlined, UserAddOutlined, SettingOutlined, UsergroupAddOutlined, DollarCircleOutlined, FolderOpenOutlined, NotificationOutlined, BellOutlined, FileTextOutlined, ProjectOutlined } from '@ant-design/icons';
import AppConsts from '../../lib/appconst';

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
  {
    path: '/user/forgotPassword',
    // permission: '',
    title: 'Forgot Password',
    name: 'ForgotPassword',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Login/forgotPassword')),
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    permission: '',
    title: 'Dashboard',
    icon: HomeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  },
  {
    path: '/administration/users',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Users',
    name: 'user',
    icon: UserOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  // {
  //   path: '/dynamicForm',
  //   permission: '',
  //   title: 'Dynamic',
  //   name: 'Form',
  //   icon: UserOutlined,
  //   showInMenu: true,
  //   component: LoadableComponent(() => import('../../scenes/DyanmicForm')),
  // },
  // {
  //   path: '/roles',
  //   permission: 'Pages.Roles',
  //   title: 'Roles',
  //   name: 'role',
  //   icon: TagsOutlined,
  //   showInMenu: true,
  //   component: LoadableComponent(() => import('../../scenes/Roles')),
  // },
  {
    path: '/campaigns',
    permission: AppConsts.permissionNames.Campaign_View,
    title: 'Campaigns',
    name: 'campaigns',
    icon: FundOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Campaigns')),
  },
  {
    path: '/products',
    permission: AppConsts.permissionNames.Product_View,
    title: 'Products',
    name: 'products',
    icon: CodeSandboxOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Products')),
  },

  {
    path: '/orders',
    permission: AppConsts.permissionNames.Order_View,
    title: 'Orders',
    name: 'orders',
    icon: ShoppingCartOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Orders')),
  },
  {
    path: '/transfer',
    permission: AppConsts.permissionNames.Transfer_View,
    title: 'Transfers',
    name: 'transfer',
    icon: RetweetOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Transfer')),
  },
  {
    path: '/transferPoint',
    permission: AppConsts.permissionNames.Transfer_Point_View,
    title: 'Transfer Point',
    name: 'transfer Point',
    icon: AppstoreAddOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/TransferPoint')),
  },
  {
    path: '/p2pTransfer',
    permission: AppConsts.permissionNames.P2PTransfer_View,
    title: 'Point To Point Transfer',
    name: 'pointToPointTransfer',
    icon: ColumnWidthOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/PointToPointTransfer')),
  },
  {
    path: '/cashOut',
    permission: AppConsts.permissionNames.Cashout_View,
    title: 'Cash Out',
    name: 'cashout',
    icon: LogoutOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/CashOut')),
  },
  {
    path: '/orphanSponsorshipCancellation',
    permission: AppConsts.permissionNames.NRE_REPORT_VIEW,
    title: 'Cancel Orphan Sponsorship',
    name: 'orphanSponsorShipCancellation',
    icon: UsergroupDeleteOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/OrphanSponsorshipCancellation')),
  },
  {
    path: '/supporters',
    permission: AppConsts.permissionNames.SUPPORTERS_LIST_VIEW,
    title: 'Supporters',
    name: 'supporters',
    icon: UsergroupAddOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Supporters')),
  },

  {
    path: '/currencies',
    permission: AppConsts.permissionNames.CURRENCY_EDIT,
    title: 'Currency Rates',
    name: 'currencies',
    icon: DollarCircleOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Currencies')),
  },

  // {
  //   path: '/about',
  //   permission: '',
  //   title: 'About',
  //   name: 'about',
  //   icon: InfoCircleOutlined,
  //   showInMenu: true,
  //   component: LoadableComponent(() => import('../../scenes/About')),
  // },
  {
    path: '/administration/allcontent',
    permission: AppConsts.permissionNames.All_Content,
    title: 'All Content',
    name: 'allcontent',
    icon: UnorderedListOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Content')),
  },
  {
    path: '/administration',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Administration',
    name: 'administration',
    icon: SettingOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Administration')),
  },
  {
    path: '/administration/countries',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Countries',
    name: 'countries',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/Countries')),
  },
  {
    path: '/administration/currencies',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Currencies',
    name: 'Currencies',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/Currencies')),
  },
  {
    path: '/administration/htmlTemplates',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Html Templates',
    name: 'htmlTemplates',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/HtmlTemplates')),
  },
  {
    path: '/administration/status',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Status',
    name: 'status',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/Status')),
  },
  {
    path: '/administration/allcontent/content',
    permission: AppConsts.permissionNames.All_Content,
    title: 'View & Manage Content',
    name: 'content',
    icon: UnorderedListOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/CRUDView')),
  },
  {
    path: '/campaigns/participants',
    permission: AppConsts.permissionNames.Campaign_Participant,
    title: 'Participants',
    name: 'participants',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Campaigns/components/participants')),
  },
  {
    path: '/administration/programCategories',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Program Categories',
    name: 'programCategories',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/ProgramCategories')),
  },
  {
    path: '/administration/programs',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Programs',
    name: 'programs',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/Programs')),
  },
  {
    path: '/administration/productForms',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Product Forms',
    name: 'productForms',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/ProductForms')),
  },
  {
    path: '/administration/products',
    permission: AppConsts.permissionNames.Admin_Access,
    title: 'Product',
    name: 'products',
    icon: SettingOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Administration/components/Products')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
  {
    path: '/profile',
    // permission: '',
    title: 'Profile',
    name: 'Profile',
    icon: ProfileOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Profile')),
  },
  {
    path: '/appUpdates',
    permission: AppConsts.permissionNames.Notifications_Manage,
    title: 'App Updates',
    name: 'App Updates',
    icon: NotificationOutlined,
    showInMenu: true,
    //component: LoadableComponent(() => import('../../scenes/Reports')),
    childRoutes: [
      {
        path: '/appUpdates/akhyarUpdates',
        permission: AppConsts.permissionNames.Notifications_Manage,
        title: 'Akhyar Updates',
        name: 'Akhyar Updates',
        icon: BellOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/AkhyarUpdates')),
      },
    ]
  },
  {
    path: '/reports',
    title: 'Reports',
    name: 'Reports',
    icon: FolderOpenOutlined,
    showInMenu: true,
    //component: LoadableComponent(() => import('../../scenes/Reports')),
    childRoutes: [
      {
        path: '/reports/orderReport',
        permission: AppConsts.permissionNames.Reports_Operations,
        title: 'Operations Report',
        name: 'Operations Report',
        icon: FileDoneOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/components/orderReport')),
      },
      {
        path: '/reports/NREReport',
        permission: AppConsts.permissionNames.NRE_REPORT_VIEW,
        title: 'NRE Report',
        name: 'nreReport',
        icon: UsergroupAddOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/NREReport')),
      },
      {
        path: '/reports/campaignsReport',
        permission: AppConsts.permissionNames.Reports_AKH_Country_Rankings,
        title: 'Akhyar Country Rankings',
        name: 'campaignsReport',
        icon: FileTextOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/Akhyar/AkhCampaignsRankings')),
      },
      {
        path: '/reports/campaignWiseRepProgressReport',
        permission: AppConsts.permissionNames.Reports_AKH_Rep_Progress,
        title: 'Rep Progress Report',
        name: 'RepProgressReport',
        icon: ProjectOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/Akhyar/CampaignWiseRepProgressReport')),
      },
      {
        path: '/reports/transferPackagesReport',
        permission: AppConsts.permissionNames.Reports_TransferPackageReport,
        title: 'Transfer Packages Report',
        name: 'TransferPackagesReport',
        icon: ProjectOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/TransferPackagesReport')),
      },
      {
        path: '/reports/khumsReport',
        permission: AppConsts.permissionNames.Reports_AKH_Khums_Report,
        title: 'Khums Report',
        name: 'KhumsReport',
        icon: ProjectOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/Akhyar/KhumsReport')),
      },
      {
        path: '/reports/AnfOrderReport',
        permission: AppConsts.permissionNames.Reports_ANF_Operations,// make new permission
        title: 'ANF Operations Report',
        name: 'Operations Report',
        icon: FileDoneOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/ANF/OperationReport')),
      },
      {
        path: '/reports/AnfKhumsReport',
        permission: AppConsts.permissionNames.Reports_ANF_Khums_Report,// make new permission
        title: 'ANF Khums Report',
        name: 'KhumsReport',
        icon: ProjectOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/ANF/KhumsReport')),
      },
      {
        path: '/reports/sadaqahRequestReport',
        //permission: AppConsts.permissionNames.Reports_SDQ_Request_Report,// make new permission
        title: 'Sadaqah Request Report',
        name: 'SadaqahRequestReport',
        icon: ProjectOutlined,
        showInMenu: true,
        component: LoadableComponent(() => import('../../scenes/Reports/SadaqahRequestReport')),
      },

    ]
  }
];

export const routers = [...userRouter, ...appRouters];
